---
title: "Cleaning and Feature Engineering"
format: html
editor: visual
---

Install and load dependencies

```{r}
if (!requireNamespace("pacman", quietly = TRUE)) install.packages("pacman")
pacman::p_load(tidyverse, lubridate, readxl, nanoparquet, visdat, dlookr, validate, naniar, usethis, purrr, arrow, slider)
```

Load data from feather file

```{r}
data <- read_feather("validated_data.feather")
```

Validation steps determined we didn't have to do any further cleaning, so feature engineering is next

Features to engineer:
[ ] wili_prop (dbl): converting wili from percentage to proportion (/100)
[ ] se (dbl): wili standard error
[ ] lower_ci (dbl): wili lower confidence interval limit
[ ] upper_ci (dbl): wili upper confidence interval limit
[ ] rolling_mean (dbl): wili rolling mean
[ ] rolling_sd (dbl): wili rolling standard deviation
[ ] cv (dbl): coefficient of variation (as a percentage)
[ ] z-score (dbl): z-score for each point
[ ] is_significant (lgl): flag significant deviations (defined as >3 SD)
[ ] yoy_change (dbl): change in wili from 52 weeks prior

```{r}
cleaned_data <- data %>%
  mutate(
    wili_prop = wili/100,
    se = sqrt((wili_prop * (1 - wili_prop)) / num_patients),
    lower_ci = (wili_prop - (1.96 * se)) * 100,
    upper_ci = (wili_prop + (1.96 * se)) * 100,
    
    rolling_mean_6wk = slider::slide_dbl(wili, mean, .before = 5),
    rolling_sd_6wk = slider::slide_dbl(wili, sd, .before = 5),
    cv_6wk = rolling_sd_6wk / rolling_mean_6wk * 100,
    z_score_6wk = (wili - rolling_mean_6wk) / rolling_sd_6wk,

    rolling_mean_20wk = slider::slide_dbl(wili, mean, .before = 19),
    rolling_sd_20wk = slider::slide_dbl(wili, sd, .before = 19),
    cv_20wk = rolling_sd_20wk / rolling_mean_20wk * 100,
    z_score_20wk = (wili - rolling_mean_20wk) / rolling_sd_20wk,

    rolling_mean_52wk = slider::slide_dbl(wili, mean, .before = 51),
    rolling_sd_52wk = slider::slide_dbl(wili, sd, .before = 51),
    cv_52wk = rolling_sd_52wk / rolling_mean_52wk * 100,
    z_score_52wk = (wili - rolling_mean_52wk) / rolling_sd_52wk,

    is_sig_6wk = abs(z_score_6wk) > 2,
    is_sig_20wk = abs(z_score_20wk) > 2,
    is_sig_52wk = abs(z_score_52wk) > 2
  )
```

```{r}
glimpse(cleaned_data)
```

Write to feather for fast intermediate reads

```{r}
write_feather(cleaned_data, "dashboard_data.feather")
```